blank_issues_enabled: false
contact_links:
  - name: Questions about Hexo-Theme-Asycn
    url: https://github.com/MaLuns/hexo-theme-async/discussions
    about: 一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.