name: NPM Publish

on:
  push:
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: |
          cp ./README_zh-CN.md ./package/hexo-theme-async
          cp ./README.md ./package/hexo-theme-async
          node ./script/publish
          yarn lib:build
        env:
          RELEASE_VERSION: ${{ github.ref }}
      
      - name: Beta Publish
        if: ${{ contains(github.ref,'beta') }}
        run: |
          cd ./package/hexo-theme-async
          npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        if: ${{ !contains(github.ref,'beta') }}
        run: |
          cd ./package/hexo-theme-async
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}